### ISSUE TITLE
final_model.py 裡面的小疑問

### ISSUE THREAD

**Issue by swilly0906** [InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction#1]
您好:
我是這個比賽的參賽者
但我名次沒有很好QQ
大概前30%左右(PR70的概念)

我認真花了一些時間研究您的modeling

有3個小疑問 想跟您請益
1.[KNN model](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L134)為什麼會用min(7, len(x), len(oof_x)? 因為我認為x跟oof_x 就是一個1萬1千多筆的資料 那一定最後會取值7吧? 有點不太懂當初設計這樣背後的邏輯想法是什麼@@????

2.[相關性](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L259) 這邊我有點不清楚 怎麼用打字表達我的疑惑 您寫到特徵不可以是mean 所以就代表 是median/std/min/max等類型特徵 不過為什麼要特別排除有mean字眼的feature 且 相關性>0.999的 ? ???

3.[epochs](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L553) 這邊我只是好奇 為何會想多*1.1 ???? 如果是我 可能頂多 寫後面的sum/n-fold 的平均次數就好了

**Comment by InfiniteWing** [comment]
您好：

我介紹一下原因
> 1.[KNN model](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L134)為什麼會用min(7, len(x), len(oof_x)? 因為我認為x跟oof_x 就是一個1萬1千多筆的資料 那一定最後會取值7吧? 有點不太懂當初設計這樣背後的邏輯想法是什麼@@????

這個是因為我有拿KNN去測別的東西，在Kaggle上面有些比賽有用到KNN達到不錯的效果，但他們會用不同的方式先把資料分群。印象中我一開始有測試用了縣市、鄉鎮和路名去分，如果用路名的話有些資料是太少的，所以才有那樣的設計避免報錯。

> 2.[相關性](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L259) 這邊我有點不清楚 怎麼用打字表達我的疑惑 您寫到特徵不可以是mean 所以就代表 是median/std/min/max等類型特徵 不過為什麼要特別排除有mean字眼的feature 且 相關性>0.999的 ? ???

一個是因為_mean的資料我後面有拿來給KNN，如果刪掉的話後面會報錯，第二個是因為雖然相關性高，但我印象中有加的話好像還是能讓tree model學得比較好，所以就沒有特別處理這塊。

> 3.[epochs](https://github.com/InfiniteWing/TBrain-2023-SinoPac-AIGO-House-Price-Prediction/blob/b9b676e0766d49d47b10aeeb331d398b3d8f7ead/%E7%A8%8B%E5%BC%8F%E7%A2%BC%E6%AA%94%E6%A1%88/final_model.py#L553) 這邊我只是好奇 為何會想多*1.1 ???? 如果是我 可能頂多 寫後面的sum/n-fold 的平均次數就好了

這邊是因為我想讓模型學得更深一些，加上pseudo後其實他很難early stopping，但我又不想讓模型太overfit，所以才用了1.1這樣的magic parameter

2, 3點是可以設計更完善的實驗來找到比較合適的方法，但因為時間有限(我是十月底參賽的)，所以就只能依照過往經驗跟Leaderboard的回饋來找到堪用的parameters (例如0.999跟1.1這樣)，實際上可以把他們歸成magic parameters

希望有回答到您

**Comment by swilly0906** [comment]
感謝 有解答我的疑惑
其實就是資料科學的流程吧
要一直反覆實驗設計出更好的做法
確實每個人的時間都是有限XD

感謝
我懂了
